// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AreaCountsById
//     Last Modified On: 12/26/2025 8:17:45 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the AreaCountsById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand AreaCountsById_BuildCommand(SqlConnection cnn, AreaCountsByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[AreaCountsById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void AreaCountsById_SetParameters(SqlCommand cmd, AreaCountsByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (AreaCountsByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private AreaCountsByIdResult AreaCountsById_ResultData(SqlDataReader rdr)
        {
            return new AreaCountsByIdResult(
            rdr.GetInt32(0),
            rdr.GetInt32(1),
            rdr.GetInt32(2),
            rdr.GetInt32(3),
            rdr.GetDecimal(4),
            rdr.GetBoolean(5),
            rdr.GetDateTime(6),
            rdr.GetDateTime(7)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void AreaCountsById_Execute(SqlCommand cmd, AreaCountsByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = AreaCountsById_ResultData(rdr);
                }
                rdr.Close();
            }

            AreaCountsById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task AreaCountsById_ExecuteAsync(SqlCommand cmd, AreaCountsByIdOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if (await rdr.ReadAsync())
                {
                    output.ResultData = AreaCountsById_ResultData(rdr);
                }
                await rdr.CloseAsync();
            }

            AreaCountsById_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Selects single row from dbo.AreaCounts table by identity column.<br/>
        /// DB Routine: dbo.AreaCountsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">AreaCountsByIdInput instance.</param>
        /// <returns>Instance of AreaCountsByIdOutput</returns>
        public AreaCountsByIdOutput AreaCountsById(AreaCountsByIdInput input)
        {
            ValidateInput(input, nameof(AreaCountsById));
            AreaCountsByIdOutput output = new AreaCountsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = AreaCountsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    AreaCountsById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = AreaCountsById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						AreaCountsById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Selects single row from dbo.AreaCounts table by identity column.<br/>
        /// DB Routine: dbo.AreaCountsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">AreaCountsByIdInput instance.</param>
        /// <returns>Instance of AreaCountsByIdOutput</returns>
        public async Task<AreaCountsByIdOutput> AreaCountsByIdAsync(AreaCountsByIdInput input)
        {
            ValidateInput(input, nameof(AreaCountsByIdAsync));
            AreaCountsByIdOutput output = new AreaCountsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = AreaCountsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await AreaCountsById_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = AreaCountsById_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await AreaCountsById_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

