// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AreaCountsUpsert
//     Last Modified On: 12/27/2025 6:39:53 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the AreaCountsUpsert routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand AreaCountsUpsert_BuildCommand(SqlConnection cnn, AreaCountsUpsertInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[AreaCountsUpsert]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.InputOutput,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@InventoryItemId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.InventoryItemId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@AreaId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.AreaId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@FullUnits",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.FullUnits
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@PartialAmount",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 1,
                Precision = 4,
                Value = input.PartialAmount
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@HasPartial",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = input.HasPartial
            });

            if (input.Id != null)
            {
                result.Parameters["@Id"].Value = input.Id;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void AreaCountsUpsert_SetParameters(SqlCommand cmd, AreaCountsUpsertOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (AreaCountsUpsertOutput.Returns)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.Id = (int?)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void AreaCountsUpsert_Execute(SqlCommand cmd, AreaCountsUpsertOutput output)
        {
            cmd.ExecuteNonQuery();

            AreaCountsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task AreaCountsUpsert_ExecuteAsync(SqlCommand cmd, AreaCountsUpsertOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            AreaCountsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Upserts a new record into the dbo.AreaCounts table.<br/>
        /// DB Routine: dbo.AreaCountsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">AreaCountsUpsertInput instance.</param>
        /// <returns>Instance of AreaCountsUpsertOutput</returns>
        public AreaCountsUpsertOutput AreaCountsUpsert(AreaCountsUpsertInput input)
        {
            ValidateInput(input, nameof(AreaCountsUpsert));
            AreaCountsUpsertOutput output = new AreaCountsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = AreaCountsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    AreaCountsUpsert_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = AreaCountsUpsert_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						AreaCountsUpsert_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Upserts a new record into the dbo.AreaCounts table.<br/>
        /// DB Routine: dbo.AreaCountsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">AreaCountsUpsertInput instance.</param>
        /// <returns>Instance of AreaCountsUpsertOutput</returns>
        public async Task<AreaCountsUpsertOutput> AreaCountsUpsertAsync(AreaCountsUpsertInput input)
        {
            ValidateInput(input, nameof(AreaCountsUpsertAsync));
            AreaCountsUpsertOutput output = new AreaCountsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = AreaCountsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await AreaCountsUpsert_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = AreaCountsUpsert_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await AreaCountsUpsert_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

