// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AreaCountsQuery
//     Last Modified On: 12/26/2025 8:28:00 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the AreaCountsQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand AreaCountsQuery_BuildCommand(SqlConnection cnn, AreaCountsQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[AreaCountsQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@InventoryItemId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@AreaId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@HasPartial",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = DBNull.Value
            });

            if (input.InventoryItemId != null)
            {
                result.Parameters["@InventoryItemId"].Value = input.InventoryItemId;
            }
            if (input.AreaId != null)
            {
                result.Parameters["@AreaId"].Value = input.AreaId;
            }
            if (input.HasPartial != null)
            {
                result.Parameters["@HasPartial"].Value = input.HasPartial;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void AreaCountsQuery_SetParameters(SqlCommand cmd, AreaCountsQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (AreaCountsQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private AreaCountsQueryResult AreaCountsQuery_ResultData(SqlDataReader rdr)
        {
            return new AreaCountsQueryResult(
            rdr.GetInt32(0),
            rdr.GetInt32(1),
            rdr.GetInt32(2),
            rdr.GetInt32(3),
            rdr.GetDecimal(4),
            rdr.GetBoolean(5),
            rdr.GetDateTime(6),
            rdr.GetDateTime(7)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void AreaCountsQuery_Execute(SqlCommand cmd, AreaCountsQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<AreaCountsQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(AreaCountsQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            AreaCountsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task AreaCountsQuery_ExecuteAsync(SqlCommand cmd, AreaCountsQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<AreaCountsQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(AreaCountsQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            AreaCountsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.AreaCounts table.<br/>
        /// DB Routine: dbo.AreaCountsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">AreaCountsQueryInput instance.</param>
        /// <returns>Instance of AreaCountsQueryOutput</returns>
        public AreaCountsQueryOutput AreaCountsQuery(AreaCountsQueryInput input)
        {
            ValidateInput(input, nameof(AreaCountsQuery));
            AreaCountsQueryOutput output = new AreaCountsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = AreaCountsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    AreaCountsQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = AreaCountsQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						AreaCountsQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.AreaCounts table.<br/>
        /// DB Routine: dbo.AreaCountsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">AreaCountsQueryInput instance.</param>
        /// <returns>Instance of AreaCountsQueryOutput</returns>
        public async Task<AreaCountsQueryOutput> AreaCountsQueryAsync(AreaCountsQueryInput input)
        {
            ValidateInput(input, nameof(AreaCountsQueryAsync));
            AreaCountsQueryOutput output = new AreaCountsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = AreaCountsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await AreaCountsQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = AreaCountsQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await AreaCountsQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

