// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ContainerTypesQuery
//     Last Modified On: 12/27/2025 12:41:15 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the ContainerTypesQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand ContainerTypesQuery_BuildCommand(SqlConnection cnn, ContainerTypesQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[ContainerTypesQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Name",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SortOrder",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsActive",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = DBNull.Value
            });

            if (input.Name != null)
            {
                result.Parameters["@Name"].Value = input.Name;
            }
            if (input.SortOrder != null)
            {
                result.Parameters["@SortOrder"].Value = input.SortOrder;
            }
            if (input.IsActive != null)
            {
                result.Parameters["@IsActive"].Value = input.IsActive;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void ContainerTypesQuery_SetParameters(SqlCommand cmd, ContainerTypesQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (ContainerTypesQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private ContainerTypesQueryResult ContainerTypesQuery_ResultData(SqlDataReader rdr)
        {
            return new ContainerTypesQueryResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetInt32(2),
            rdr.GetBoolean(3),
            rdr.GetDateTime(4),
            rdr.GetDateTime(5)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void ContainerTypesQuery_Execute(SqlCommand cmd, ContainerTypesQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<ContainerTypesQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(ContainerTypesQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            ContainerTypesQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task ContainerTypesQuery_ExecuteAsync(SqlCommand cmd, ContainerTypesQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<ContainerTypesQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(ContainerTypesQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            ContainerTypesQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.ContainerTypes table.<br/>
        /// DB Routine: dbo.ContainerTypesQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ContainerTypesQueryInput instance.</param>
        /// <returns>Instance of ContainerTypesQueryOutput</returns>
        public ContainerTypesQueryOutput ContainerTypesQuery(ContainerTypesQueryInput input)
        {
            ValidateInput(input, nameof(ContainerTypesQuery));
            ContainerTypesQueryOutput output = new ContainerTypesQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ContainerTypesQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    ContainerTypesQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ContainerTypesQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						ContainerTypesQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.ContainerTypes table.<br/>
        /// DB Routine: dbo.ContainerTypesQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ContainerTypesQueryInput instance.</param>
        /// <returns>Instance of ContainerTypesQueryOutput</returns>
        public async Task<ContainerTypesQueryOutput> ContainerTypesQueryAsync(ContainerTypesQueryInput input)
        {
            ValidateInput(input, nameof(ContainerTypesQueryAsync));
            ContainerTypesQueryOutput output = new ContainerTypesQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ContainerTypesQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await ContainerTypesQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ContainerTypesQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await ContainerTypesQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

