// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryAreasQuery
//     Last Modified On: 12/26/2025 8:27:14 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventoryAreasQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventoryAreasQuery_BuildCommand(SqlConnection cnn, InventoryAreasQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventoryAreasQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Name",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 100,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ShortCode",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsActive",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = DBNull.Value
            });

            if (input.Name != null)
            {
                result.Parameters["@Name"].Value = input.Name;
            }
            if (input.ShortCode != null)
            {
                result.Parameters["@ShortCode"].Value = input.ShortCode;
            }
            if (input.IsActive != null)
            {
                result.Parameters["@IsActive"].Value = input.IsActive;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventoryAreasQuery_SetParameters(SqlCommand cmd, InventoryAreasQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventoryAreasQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private InventoryAreasQueryResult InventoryAreasQuery_ResultData(SqlDataReader rdr)
        {
            return new InventoryAreasQueryResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetString(2),
            rdr.GetInt32(3),
            rdr.GetBoolean(4),
            rdr.GetDateTime(5),
            rdr.GetDateTime(6)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void InventoryAreasQuery_Execute(SqlCommand cmd, InventoryAreasQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<InventoryAreasQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(InventoryAreasQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            InventoryAreasQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventoryAreasQuery_ExecuteAsync(SqlCommand cmd, InventoryAreasQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<InventoryAreasQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(InventoryAreasQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            InventoryAreasQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.InventoryAreas table.<br/>
        /// DB Routine: dbo.InventoryAreasQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryAreasQueryInput instance.</param>
        /// <returns>Instance of InventoryAreasQueryOutput</returns>
        public InventoryAreasQueryOutput InventoryAreasQuery(InventoryAreasQueryInput input)
        {
            ValidateInput(input, nameof(InventoryAreasQuery));
            InventoryAreasQueryOutput output = new InventoryAreasQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryAreasQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventoryAreasQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryAreasQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventoryAreasQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.InventoryAreas table.<br/>
        /// DB Routine: dbo.InventoryAreasQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryAreasQueryInput instance.</param>
        /// <returns>Instance of InventoryAreasQueryOutput</returns>
        public async Task<InventoryAreasQueryOutput> InventoryAreasQueryAsync(InventoryAreasQueryInput input)
        {
            ValidateInput(input, nameof(InventoryAreasQueryAsync));
            InventoryAreasQueryOutput output = new InventoryAreasQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryAreasQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventoryAreasQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryAreasQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventoryAreasQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

