// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryItemsById
//     Last Modified On: 12/26/2025 8:32:34 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventoryItemsById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventoryItemsById_BuildCommand(SqlConnection cnn, InventoryItemsByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventoryItemsById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventoryItemsById_SetParameters(SqlCommand cmd, InventoryItemsByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventoryItemsByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private InventoryItemsByIdResult InventoryItemsById_ResultData(SqlDataReader rdr)
        {
            return new InventoryItemsByIdResult(
            rdr.GetInt32(0),
            rdr.GetInt32(1),
            rdr.GetInt32(2),
            rdr.GetDecimal(3),
            rdr.GetDecimal(4),
            rdr.GetDecimal(5),
            rdr.GetDecimal(6),
            rdr.GetDecimal(7),
            rdr.GetDecimal(8),
            rdr.IsDBNull(9) ? null : rdr.GetDateTime(9),
            rdr.GetDateTime(10),
            rdr.GetDateTime(11)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void InventoryItemsById_Execute(SqlCommand cmd, InventoryItemsByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = InventoryItemsById_ResultData(rdr);
                }
                rdr.Close();
            }

            InventoryItemsById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventoryItemsById_ExecuteAsync(SqlCommand cmd, InventoryItemsByIdOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if (await rdr.ReadAsync())
                {
                    output.ResultData = InventoryItemsById_ResultData(rdr);
                }
                await rdr.CloseAsync();
            }

            InventoryItemsById_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Selects single row from dbo.InventoryItems table by identity column.<br/>
        /// DB Routine: dbo.InventoryItemsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryItemsByIdInput instance.</param>
        /// <returns>Instance of InventoryItemsByIdOutput</returns>
        public InventoryItemsByIdOutput InventoryItemsById(InventoryItemsByIdInput input)
        {
            ValidateInput(input, nameof(InventoryItemsById));
            InventoryItemsByIdOutput output = new InventoryItemsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryItemsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventoryItemsById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryItemsById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventoryItemsById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Selects single row from dbo.InventoryItems table by identity column.<br/>
        /// DB Routine: dbo.InventoryItemsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryItemsByIdInput instance.</param>
        /// <returns>Instance of InventoryItemsByIdOutput</returns>
        public async Task<InventoryItemsByIdOutput> InventoryItemsByIdAsync(InventoryItemsByIdInput input)
        {
            ValidateInput(input, nameof(InventoryItemsByIdAsync));
            InventoryItemsByIdOutput output = new InventoryItemsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryItemsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventoryItemsById_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryItemsById_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventoryItemsById_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

