// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventorySessionsById
//     Last Modified On: 12/27/2025 12:41:17 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventorySessionsById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventorySessionsById_BuildCommand(SqlConnection cnn, InventorySessionsByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventorySessionsById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventorySessionsById_SetParameters(SqlCommand cmd, InventorySessionsByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventorySessionsByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private InventorySessionsByIdResult InventorySessionsById_ResultData(SqlDataReader rdr)
        {
            return new InventorySessionsByIdResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetDateTime(2),
            rdr.IsDBNull(3) ? null : rdr.GetDateTime(3),
            rdr.GetInt32(4),
            rdr.IsDBNull(5) ? null : rdr.GetString(5),
            rdr.GetBoolean(6),
            rdr.GetString(7),
            rdr.GetDateTime(8),
            rdr.GetDateTime(9)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void InventorySessionsById_Execute(SqlCommand cmd, InventorySessionsByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = InventorySessionsById_ResultData(rdr);
                }
                rdr.Close();
            }

            InventorySessionsById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventorySessionsById_ExecuteAsync(SqlCommand cmd, InventorySessionsByIdOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if (await rdr.ReadAsync())
                {
                    output.ResultData = InventorySessionsById_ResultData(rdr);
                }
                await rdr.CloseAsync();
            }

            InventorySessionsById_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Selects single row from dbo.InventorySessions table by identity column.<br/>
        /// DB Routine: dbo.InventorySessionsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventorySessionsByIdInput instance.</param>
        /// <returns>Instance of InventorySessionsByIdOutput</returns>
        public InventorySessionsByIdOutput InventorySessionsById(InventorySessionsByIdInput input)
        {
            ValidateInput(input, nameof(InventorySessionsById));
            InventorySessionsByIdOutput output = new InventorySessionsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventorySessionsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventorySessionsById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventorySessionsById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventorySessionsById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Selects single row from dbo.InventorySessions table by identity column.<br/>
        /// DB Routine: dbo.InventorySessionsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventorySessionsByIdInput instance.</param>
        /// <returns>Instance of InventorySessionsByIdOutput</returns>
        public async Task<InventorySessionsByIdOutput> InventorySessionsByIdAsync(InventorySessionsByIdInput input)
        {
            ValidateInput(input, nameof(InventorySessionsByIdAsync));
            InventorySessionsByIdOutput output = new InventorySessionsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventorySessionsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventorySessionsById_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventorySessionsById_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventorySessionsById_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

