// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventorySessionsQuery
//     Last Modified On: 12/26/2025 9:03:50 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventorySessionsQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventorySessionsQuery_BuildCommand(SqlConnection cnn, InventorySessionsQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventorySessionsQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SessionName",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 200,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsComplete",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CountedBy",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 100,
                Value = DBNull.Value
            });

            if (input.SessionName != null)
            {
                result.Parameters["@SessionName"].Value = input.SessionName;
            }
            if (input.IsComplete != null)
            {
                result.Parameters["@IsComplete"].Value = input.IsComplete;
            }
            if (input.CountedBy != null)
            {
                result.Parameters["@CountedBy"].Value = input.CountedBy;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventorySessionsQuery_SetParameters(SqlCommand cmd, InventorySessionsQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventorySessionsQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private InventorySessionsQueryResult InventorySessionsQuery_ResultData(SqlDataReader rdr)
        {
            return new InventorySessionsQueryResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetDateTime(2),
            rdr.IsDBNull(3) ? null : rdr.GetDateTime(3),
            rdr.GetByte(4),
            rdr.IsDBNull(5) ? null : rdr.GetString(5),
            rdr.GetBoolean(6),
            rdr.GetString(7),
            rdr.GetDateTime(8),
            rdr.GetDateTime(9)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void InventorySessionsQuery_Execute(SqlCommand cmd, InventorySessionsQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<InventorySessionsQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(InventorySessionsQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            InventorySessionsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventorySessionsQuery_ExecuteAsync(SqlCommand cmd, InventorySessionsQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<InventorySessionsQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(InventorySessionsQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            InventorySessionsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.InventorySessions table.<br/>
        /// DB Routine: dbo.InventorySessionsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventorySessionsQueryInput instance.</param>
        /// <returns>Instance of InventorySessionsQueryOutput</returns>
        public InventorySessionsQueryOutput InventorySessionsQuery(InventorySessionsQueryInput input)
        {
            ValidateInput(input, nameof(InventorySessionsQuery));
            InventorySessionsQueryOutput output = new InventorySessionsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventorySessionsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventorySessionsQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventorySessionsQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventorySessionsQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.InventorySessions table.<br/>
        /// DB Routine: dbo.InventorySessionsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventorySessionsQueryInput instance.</param>
        /// <returns>Instance of InventorySessionsQueryOutput</returns>
        public async Task<InventorySessionsQueryOutput> InventorySessionsQueryAsync(InventorySessionsQueryInput input)
        {
            ValidateInput(input, nameof(InventorySessionsQueryAsync));
            InventorySessionsQueryOutput output = new InventorySessionsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventorySessionsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventorySessionsQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventorySessionsQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventorySessionsQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

