// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryItemsQuery
//     Last Modified On: 12/27/2025 12:41:17 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventoryItemsQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventoryItemsQuery_BuildCommand(SqlConnection cnn, InventoryItemsQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventoryItemsQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SessionId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ProductId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            if (input.SessionId != null)
            {
                result.Parameters["@SessionId"].Value = input.SessionId;
            }
            if (input.ProductId != null)
            {
                result.Parameters["@ProductId"].Value = input.ProductId;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventoryItemsQuery_SetParameters(SqlCommand cmd, InventoryItemsQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventoryItemsQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private InventoryItemsQueryResult InventoryItemsQuery_ResultData(SqlDataReader rdr)
        {
            return new InventoryItemsQueryResult(
            rdr.GetInt32(0),
            rdr.GetInt32(1),
            rdr.GetInt32(2),
            rdr.GetDecimal(3),
            rdr.GetDecimal(4),
            rdr.GetDecimal(5),
            rdr.GetDecimal(6),
            rdr.GetDecimal(7),
            rdr.GetDecimal(8),
            rdr.IsDBNull(9) ? null : rdr.GetDateTime(9),
            rdr.GetDateTime(10),
            rdr.GetDateTime(11)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void InventoryItemsQuery_Execute(SqlCommand cmd, InventoryItemsQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<InventoryItemsQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(InventoryItemsQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            InventoryItemsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventoryItemsQuery_ExecuteAsync(SqlCommand cmd, InventoryItemsQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<InventoryItemsQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(InventoryItemsQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            InventoryItemsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.InventoryItems table.<br/>
        /// DB Routine: dbo.InventoryItemsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryItemsQueryInput instance.</param>
        /// <returns>Instance of InventoryItemsQueryOutput</returns>
        public InventoryItemsQueryOutput InventoryItemsQuery(InventoryItemsQueryInput input)
        {
            ValidateInput(input, nameof(InventoryItemsQuery));
            InventoryItemsQueryOutput output = new InventoryItemsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryItemsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventoryItemsQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryItemsQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventoryItemsQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.InventoryItems table.<br/>
        /// DB Routine: dbo.InventoryItemsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryItemsQueryInput instance.</param>
        /// <returns>Instance of InventoryItemsQueryOutput</returns>
        public async Task<InventoryItemsQueryOutput> InventoryItemsQueryAsync(InventoryItemsQueryInput input)
        {
            ValidateInput(input, nameof(InventoryItemsQueryAsync));
            InventoryItemsQueryOutput output = new InventoryItemsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryItemsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventoryItemsQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryItemsQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventoryItemsQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

