// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryFrequenciesUpsert
//     Last Modified On: 12/27/2025 6:39:29 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventoryFrequenciesUpsert routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventoryFrequenciesUpsert_BuildCommand(SqlConnection cnn, InventoryFrequenciesUpsertInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventoryFrequenciesUpsert]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.InputOutput,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Name",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = input.Name
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SortOrder",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.SortOrder
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsActive",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = input.IsActive
            });

            if (input.Id != null)
            {
                result.Parameters["@Id"].Value = input.Id;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventoryFrequenciesUpsert_SetParameters(SqlCommand cmd, InventoryFrequenciesUpsertOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventoryFrequenciesUpsertOutput.Returns)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.Id = (int?)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void InventoryFrequenciesUpsert_Execute(SqlCommand cmd, InventoryFrequenciesUpsertOutput output)
        {
            cmd.ExecuteNonQuery();

            InventoryFrequenciesUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventoryFrequenciesUpsert_ExecuteAsync(SqlCommand cmd, InventoryFrequenciesUpsertOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            InventoryFrequenciesUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Upserts a new record into the dbo.InventoryFrequencies table.<br/>
        /// DB Routine: dbo.InventoryFrequenciesUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryFrequenciesUpsertInput instance.</param>
        /// <returns>Instance of InventoryFrequenciesUpsertOutput</returns>
        public InventoryFrequenciesUpsertOutput InventoryFrequenciesUpsert(InventoryFrequenciesUpsertInput input)
        {
            ValidateInput(input, nameof(InventoryFrequenciesUpsert));
            InventoryFrequenciesUpsertOutput output = new InventoryFrequenciesUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryFrequenciesUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventoryFrequenciesUpsert_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryFrequenciesUpsert_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventoryFrequenciesUpsert_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Upserts a new record into the dbo.InventoryFrequencies table.<br/>
        /// DB Routine: dbo.InventoryFrequenciesUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryFrequenciesUpsertInput instance.</param>
        /// <returns>Instance of InventoryFrequenciesUpsertOutput</returns>
        public async Task<InventoryFrequenciesUpsertOutput> InventoryFrequenciesUpsertAsync(InventoryFrequenciesUpsertInput input)
        {
            ValidateInput(input, nameof(InventoryFrequenciesUpsertAsync));
            InventoryFrequenciesUpsertOutput output = new InventoryFrequenciesUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryFrequenciesUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventoryFrequenciesUpsert_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryFrequenciesUpsert_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventoryFrequenciesUpsert_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

