// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryItemsUpsert
//     Last Modified On: 12/26/2025 8:59:37 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventoryItemsUpsert routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventoryItemsUpsert_BuildCommand(SqlConnection cnn, InventoryItemsUpsertInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventoryItemsUpsert]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.InputOutput,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SessionId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.SessionId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ProductId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.ProductId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@UnitCost",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.UnitCost
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@StartingQuantity",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.StartingQuantity
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReceivedQuantity",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.ReceivedQuantity
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReceivedCost",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.ReceivedCost
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ComputerSold",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.ComputerSold
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CreditedProduct",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.CreditedProduct
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@LastCountedAt",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.DateTime2,
                Precision = 7,
                Value = DBNull.Value
            });

            if (input.LastCountedAt != null)
            {
                result.Parameters["@LastCountedAt"].Value = input.LastCountedAt;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventoryItemsUpsert_SetParameters(SqlCommand cmd, InventoryItemsUpsertOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventoryItemsUpsertOutput.Returns)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.Id = (int?)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void InventoryItemsUpsert_Execute(SqlCommand cmd, InventoryItemsUpsertOutput output)
        {
            cmd.ExecuteNonQuery();

            InventoryItemsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventoryItemsUpsert_ExecuteAsync(SqlCommand cmd, InventoryItemsUpsertOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            InventoryItemsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Upserts a new record into the dbo.InventoryItems table.<br/>
        /// DB Routine: dbo.InventoryItemsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryItemsUpsertInput instance.</param>
        /// <returns>Instance of InventoryItemsUpsertOutput</returns>
        public InventoryItemsUpsertOutput InventoryItemsUpsert(InventoryItemsUpsertInput input)
        {
            ValidateInput(input, nameof(InventoryItemsUpsert));
            InventoryItemsUpsertOutput output = new InventoryItemsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryItemsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventoryItemsUpsert_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryItemsUpsert_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventoryItemsUpsert_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Upserts a new record into the dbo.InventoryItems table.<br/>
        /// DB Routine: dbo.InventoryItemsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryItemsUpsertInput instance.</param>
        /// <returns>Instance of InventoryItemsUpsertOutput</returns>
        public async Task<InventoryItemsUpsertOutput> InventoryItemsUpsertAsync(InventoryItemsUpsertInput input)
        {
            ValidateInput(input, nameof(InventoryItemsUpsertAsync));
            InventoryItemsUpsertOutput output = new InventoryItemsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryItemsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventoryItemsUpsert_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryItemsUpsert_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventoryItemsUpsert_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

