// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryAreasById
//     Last Modified On: 12/27/2025 12:41:15 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventoryAreasById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventoryAreasById_BuildCommand(SqlConnection cnn, InventoryAreasByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventoryAreasById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventoryAreasById_SetParameters(SqlCommand cmd, InventoryAreasByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventoryAreasByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private InventoryAreasByIdResult InventoryAreasById_ResultData(SqlDataReader rdr)
        {
            return new InventoryAreasByIdResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetString(2),
            rdr.GetInt32(3),
            rdr.GetBoolean(4),
            rdr.GetDateTime(5),
            rdr.GetDateTime(6)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void InventoryAreasById_Execute(SqlCommand cmd, InventoryAreasByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = InventoryAreasById_ResultData(rdr);
                }
                rdr.Close();
            }

            InventoryAreasById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventoryAreasById_ExecuteAsync(SqlCommand cmd, InventoryAreasByIdOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if (await rdr.ReadAsync())
                {
                    output.ResultData = InventoryAreasById_ResultData(rdr);
                }
                await rdr.CloseAsync();
            }

            InventoryAreasById_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Selects single row from dbo.InventoryAreas table by identity column.<br/>
        /// DB Routine: dbo.InventoryAreasById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryAreasByIdInput instance.</param>
        /// <returns>Instance of InventoryAreasByIdOutput</returns>
        public InventoryAreasByIdOutput InventoryAreasById(InventoryAreasByIdInput input)
        {
            ValidateInput(input, nameof(InventoryAreasById));
            InventoryAreasByIdOutput output = new InventoryAreasByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryAreasById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventoryAreasById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryAreasById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventoryAreasById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Selects single row from dbo.InventoryAreas table by identity column.<br/>
        /// DB Routine: dbo.InventoryAreasById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryAreasByIdInput instance.</param>
        /// <returns>Instance of InventoryAreasByIdOutput</returns>
        public async Task<InventoryAreasByIdOutput> InventoryAreasByIdAsync(InventoryAreasByIdInput input)
        {
            ValidateInput(input, nameof(InventoryAreasByIdAsync));
            InventoryAreasByIdOutput output = new InventoryAreasByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryAreasById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventoryAreasById_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryAreasById_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventoryAreasById_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

