// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryFrequenciesDelete
//     Last Modified On: 12/26/2025 11:30:19 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventoryFrequenciesDelete routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventoryFrequenciesDelete_BuildCommand(SqlConnection cnn, InventoryFrequenciesDeleteInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventoryFrequenciesDelete]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.TinyInt,
                Scale = 0,
                Precision = 3,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventoryFrequenciesDelete_SetParameters(SqlCommand cmd, InventoryFrequenciesDeleteOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventoryFrequenciesDeleteOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void InventoryFrequenciesDelete_Execute(SqlCommand cmd, InventoryFrequenciesDeleteOutput output)
        {
            cmd.ExecuteNonQuery();

            InventoryFrequenciesDelete_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventoryFrequenciesDelete_ExecuteAsync(SqlCommand cmd, InventoryFrequenciesDeleteOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            InventoryFrequenciesDelete_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Deletes single row from dbo.InventoryFrequencies table by identity column.<br/>
        /// DB Routine: dbo.InventoryFrequenciesDelete<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryFrequenciesDeleteInput instance.</param>
        /// <returns>Instance of InventoryFrequenciesDeleteOutput</returns>
        public InventoryFrequenciesDeleteOutput InventoryFrequenciesDelete(InventoryFrequenciesDeleteInput input)
        {
            ValidateInput(input, nameof(InventoryFrequenciesDelete));
            InventoryFrequenciesDeleteOutput output = new InventoryFrequenciesDeleteOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryFrequenciesDelete_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventoryFrequenciesDelete_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryFrequenciesDelete_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventoryFrequenciesDelete_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Deletes single row from dbo.InventoryFrequencies table by identity column.<br/>
        /// DB Routine: dbo.InventoryFrequenciesDelete<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventoryFrequenciesDeleteInput instance.</param>
        /// <returns>Instance of InventoryFrequenciesDeleteOutput</returns>
        public async Task<InventoryFrequenciesDeleteOutput> InventoryFrequenciesDeleteAsync(InventoryFrequenciesDeleteInput input)
        {
            ValidateInput(input, nameof(InventoryFrequenciesDeleteAsync));
            InventoryFrequenciesDeleteOutput output = new InventoryFrequenciesDeleteOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventoryFrequenciesDelete_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventoryFrequenciesDelete_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventoryFrequenciesDelete_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventoryFrequenciesDelete_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

