// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventorySessionsUpsert
//     Last Modified On: 12/26/2025 9:08:33 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the InventorySessionsUpsert routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand InventorySessionsUpsert_BuildCommand(SqlConnection cnn, InventorySessionsUpsertInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[InventorySessionsUpsert]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.InputOutput,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SessionName",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 200,
                Value = input.SessionName
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SessionDate",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.DateTime2,
                Precision = 7,
                Value = input.SessionDate
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CompletedAt",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.DateTime2,
                Precision = 7,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Frequency",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.TinyInt,
                Scale = 0,
                Precision = 3,
                Value = input.Frequency
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Notes",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = -1,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsComplete",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = input.IsComplete
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CountedBy",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 100,
                Value = input.CountedBy
            });

            if (input.CompletedAt != null)
            {
                result.Parameters["@CompletedAt"].Value = input.CompletedAt;
            }
            if (input.Notes != null)
            {
                result.Parameters["@Notes"].Value = input.Notes;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void InventorySessionsUpsert_SetParameters(SqlCommand cmd, InventorySessionsUpsertOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (InventorySessionsUpsertOutput.Returns)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.Id = (int?)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void InventorySessionsUpsert_Execute(SqlCommand cmd, InventorySessionsUpsertOutput output)
        {
            cmd.ExecuteNonQuery();

            InventorySessionsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task InventorySessionsUpsert_ExecuteAsync(SqlCommand cmd, InventorySessionsUpsertOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            InventorySessionsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Upserts a new record into the dbo.InventorySessions table.<br/>
        /// DB Routine: dbo.InventorySessionsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventorySessionsUpsertInput instance.</param>
        /// <returns>Instance of InventorySessionsUpsertOutput</returns>
        public InventorySessionsUpsertOutput InventorySessionsUpsert(InventorySessionsUpsertInput input)
        {
            ValidateInput(input, nameof(InventorySessionsUpsert));
            InventorySessionsUpsertOutput output = new InventorySessionsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventorySessionsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    InventorySessionsUpsert_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventorySessionsUpsert_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						InventorySessionsUpsert_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Upserts a new record into the dbo.InventorySessions table.<br/>
        /// DB Routine: dbo.InventorySessionsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">InventorySessionsUpsertInput instance.</param>
        /// <returns>Instance of InventorySessionsUpsertOutput</returns>
        public async Task<InventorySessionsUpsertOutput> InventorySessionsUpsertAsync(InventorySessionsUpsertInput input)
        {
            ValidateInput(input, nameof(InventorySessionsUpsertAsync));
            InventorySessionsUpsertOutput output = new InventorySessionsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = InventorySessionsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await InventorySessionsUpsert_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = InventorySessionsUpsert_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await InventorySessionsUpsert_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

