// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossRecordsDelete
//     Last Modified On: 12/27/2025 12:41:18 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the LossRecordsDelete routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand LossRecordsDelete_BuildCommand(SqlConnection cnn, LossRecordsDeleteInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[LossRecordsDelete]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void LossRecordsDelete_SetParameters(SqlCommand cmd, LossRecordsDeleteOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (LossRecordsDeleteOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void LossRecordsDelete_Execute(SqlCommand cmd, LossRecordsDeleteOutput output)
        {
            cmd.ExecuteNonQuery();

            LossRecordsDelete_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task LossRecordsDelete_ExecuteAsync(SqlCommand cmd, LossRecordsDeleteOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            LossRecordsDelete_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Deletes single row from dbo.LossRecords table by identity column.<br/>
        /// DB Routine: dbo.LossRecordsDelete<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsDeleteInput instance.</param>
        /// <returns>Instance of LossRecordsDeleteOutput</returns>
        public LossRecordsDeleteOutput LossRecordsDelete(LossRecordsDeleteInput input)
        {
            ValidateInput(input, nameof(LossRecordsDelete));
            LossRecordsDeleteOutput output = new LossRecordsDeleteOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsDelete_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    LossRecordsDelete_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsDelete_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						LossRecordsDelete_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Deletes single row from dbo.LossRecords table by identity column.<br/>
        /// DB Routine: dbo.LossRecordsDelete<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsDeleteInput instance.</param>
        /// <returns>Instance of LossRecordsDeleteOutput</returns>
        public async Task<LossRecordsDeleteOutput> LossRecordsDeleteAsync(LossRecordsDeleteInput input)
        {
            ValidateInput(input, nameof(LossRecordsDeleteAsync));
            LossRecordsDeleteOutput output = new LossRecordsDeleteOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsDelete_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await LossRecordsDelete_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsDelete_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await LossRecordsDelete_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

