// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossRecordsQuery
//     Last Modified On: 12/26/2025 9:08:04 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the LossRecordsQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand LossRecordsQuery_BuildCommand(SqlConnection cnn, LossRecordsQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[LossRecordsQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SessionId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ProductId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@LossType",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.TinyInt,
                Scale = 0,
                Precision = 3,
                Value = DBNull.Value
            });

            if (input.SessionId != null)
            {
                result.Parameters["@SessionId"].Value = input.SessionId;
            }
            if (input.ProductId != null)
            {
                result.Parameters["@ProductId"].Value = input.ProductId;
            }
            if (input.LossType != null)
            {
                result.Parameters["@LossType"].Value = input.LossType;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void LossRecordsQuery_SetParameters(SqlCommand cmd, LossRecordsQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (LossRecordsQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private LossRecordsQueryResult LossRecordsQuery_ResultData(SqlDataReader rdr)
        {
            return new LossRecordsQueryResult(
            rdr.GetInt32(0),
            rdr.GetInt32(1),
            rdr.GetInt32(2),
            rdr.GetByte(3),
            rdr.GetDecimal(4),
            rdr.GetDecimal(5),
            rdr.IsDBNull(6) ? null : rdr.GetString(6),
            rdr.IsDBNull(7) ? null : rdr.GetString(7),
            rdr.GetDateTime(8),
            rdr.GetDateTime(9),
            rdr.GetDateTime(10)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void LossRecordsQuery_Execute(SqlCommand cmd, LossRecordsQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<LossRecordsQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(LossRecordsQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            LossRecordsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task LossRecordsQuery_ExecuteAsync(SqlCommand cmd, LossRecordsQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<LossRecordsQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(LossRecordsQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            LossRecordsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.LossRecords table.<br/>
        /// DB Routine: dbo.LossRecordsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsQueryInput instance.</param>
        /// <returns>Instance of LossRecordsQueryOutput</returns>
        public LossRecordsQueryOutput LossRecordsQuery(LossRecordsQueryInput input)
        {
            ValidateInput(input, nameof(LossRecordsQuery));
            LossRecordsQueryOutput output = new LossRecordsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    LossRecordsQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						LossRecordsQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.LossRecords table.<br/>
        /// DB Routine: dbo.LossRecordsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsQueryInput instance.</param>
        /// <returns>Instance of LossRecordsQueryOutput</returns>
        public async Task<LossRecordsQueryOutput> LossRecordsQueryAsync(LossRecordsQueryInput input)
        {
            ValidateInput(input, nameof(LossRecordsQueryAsync));
            LossRecordsQueryOutput output = new LossRecordsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await LossRecordsQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await LossRecordsQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

