// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossRecordsById
//     Last Modified On: 12/26/2025 9:08:04 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the LossRecordsById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand LossRecordsById_BuildCommand(SqlConnection cnn, LossRecordsByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[LossRecordsById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void LossRecordsById_SetParameters(SqlCommand cmd, LossRecordsByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (LossRecordsByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private LossRecordsByIdResult LossRecordsById_ResultData(SqlDataReader rdr)
        {
            return new LossRecordsByIdResult(
            rdr.GetInt32(0),
            rdr.GetInt32(1),
            rdr.GetInt32(2),
            rdr.GetByte(3),
            rdr.GetDecimal(4),
            rdr.GetDecimal(5),
            rdr.IsDBNull(6) ? null : rdr.GetString(6),
            rdr.IsDBNull(7) ? null : rdr.GetString(7),
            rdr.GetDateTime(8),
            rdr.GetDateTime(9),
            rdr.GetDateTime(10)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void LossRecordsById_Execute(SqlCommand cmd, LossRecordsByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = LossRecordsById_ResultData(rdr);
                }
                rdr.Close();
            }

            LossRecordsById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task LossRecordsById_ExecuteAsync(SqlCommand cmd, LossRecordsByIdOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if (await rdr.ReadAsync())
                {
                    output.ResultData = LossRecordsById_ResultData(rdr);
                }
                await rdr.CloseAsync();
            }

            LossRecordsById_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Selects single row from dbo.LossRecords table by identity column.<br/>
        /// DB Routine: dbo.LossRecordsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsByIdInput instance.</param>
        /// <returns>Instance of LossRecordsByIdOutput</returns>
        public LossRecordsByIdOutput LossRecordsById(LossRecordsByIdInput input)
        {
            ValidateInput(input, nameof(LossRecordsById));
            LossRecordsByIdOutput output = new LossRecordsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    LossRecordsById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						LossRecordsById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Selects single row from dbo.LossRecords table by identity column.<br/>
        /// DB Routine: dbo.LossRecordsById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsByIdInput instance.</param>
        /// <returns>Instance of LossRecordsByIdOutput</returns>
        public async Task<LossRecordsByIdOutput> LossRecordsByIdAsync(LossRecordsByIdInput input)
        {
            ValidateInput(input, nameof(LossRecordsByIdAsync));
            LossRecordsByIdOutput output = new LossRecordsByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await LossRecordsById_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsById_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await LossRecordsById_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

