// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossRecordsUpsert
//     Last Modified On: 12/27/2025 12:41:18 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the LossRecordsUpsert routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand LossRecordsUpsert_BuildCommand(SqlConnection cnn, LossRecordsUpsertInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[LossRecordsUpsert]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.InputOutput,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SessionId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.SessionId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ProductId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.ProductId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@LossType",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.LossType
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Quantity",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.Quantity
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@EstimatedValue",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.EstimatedValue
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Reason",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 500,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@RecordedBy",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 100,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@OccurredAt",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.DateTime2,
                Precision = 7,
                Value = input.OccurredAt
            });

            if (input.Reason != null)
            {
                result.Parameters["@Reason"].Value = input.Reason;
            }
            if (input.RecordedBy != null)
            {
                result.Parameters["@RecordedBy"].Value = input.RecordedBy;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void LossRecordsUpsert_SetParameters(SqlCommand cmd, LossRecordsUpsertOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (LossRecordsUpsertOutput.Returns)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.Id = (int?)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void LossRecordsUpsert_Execute(SqlCommand cmd, LossRecordsUpsertOutput output)
        {
            cmd.ExecuteNonQuery();

            LossRecordsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task LossRecordsUpsert_ExecuteAsync(SqlCommand cmd, LossRecordsUpsertOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            LossRecordsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Upserts a new record into the dbo.LossRecords table.<br/>
        /// DB Routine: dbo.LossRecordsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsUpsertInput instance.</param>
        /// <returns>Instance of LossRecordsUpsertOutput</returns>
        public LossRecordsUpsertOutput LossRecordsUpsert(LossRecordsUpsertInput input)
        {
            ValidateInput(input, nameof(LossRecordsUpsert));
            LossRecordsUpsertOutput output = new LossRecordsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    LossRecordsUpsert_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsUpsert_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						LossRecordsUpsert_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Upserts a new record into the dbo.LossRecords table.<br/>
        /// DB Routine: dbo.LossRecordsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossRecordsUpsertInput instance.</param>
        /// <returns>Instance of LossRecordsUpsertOutput</returns>
        public async Task<LossRecordsUpsertOutput> LossRecordsUpsertAsync(LossRecordsUpsertInput input)
        {
            ValidateInput(input, nameof(LossRecordsUpsertAsync));
            LossRecordsUpsertOutput output = new LossRecordsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossRecordsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await LossRecordsUpsert_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossRecordsUpsert_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await LossRecordsUpsert_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

