// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossTypesById
//     Last Modified On: 12/26/2025 11:26:43 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the LossTypesById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand LossTypesById_BuildCommand(SqlConnection cnn, LossTypesByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[LossTypesById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.TinyInt,
                Scale = 0,
                Precision = 3,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void LossTypesById_SetParameters(SqlCommand cmd, LossTypesByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (LossTypesByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private LossTypesByIdResult LossTypesById_ResultData(SqlDataReader rdr)
        {
            return new LossTypesByIdResult(
            rdr.GetByte(0),
            rdr.GetString(1),
            rdr.GetInt32(2),
            rdr.GetBoolean(3),
            rdr.GetDateTime(4),
            rdr.GetDateTime(5)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void LossTypesById_Execute(SqlCommand cmd, LossTypesByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = LossTypesById_ResultData(rdr);
                }
                rdr.Close();
            }

            LossTypesById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task LossTypesById_ExecuteAsync(SqlCommand cmd, LossTypesByIdOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if (await rdr.ReadAsync())
                {
                    output.ResultData = LossTypesById_ResultData(rdr);
                }
                await rdr.CloseAsync();
            }

            LossTypesById_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Selects single row from dbo.LossTypes table by identity column.<br/>
        /// DB Routine: dbo.LossTypesById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossTypesByIdInput instance.</param>
        /// <returns>Instance of LossTypesByIdOutput</returns>
        public LossTypesByIdOutput LossTypesById(LossTypesByIdInput input)
        {
            ValidateInput(input, nameof(LossTypesById));
            LossTypesByIdOutput output = new LossTypesByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossTypesById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    LossTypesById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossTypesById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						LossTypesById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Selects single row from dbo.LossTypes table by identity column.<br/>
        /// DB Routine: dbo.LossTypesById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">LossTypesByIdInput instance.</param>
        /// <returns>Instance of LossTypesByIdOutput</returns>
        public async Task<LossTypesByIdOutput> LossTypesByIdAsync(LossTypesByIdInput input)
        {
            ValidateInput(input, nameof(LossTypesByIdAsync));
            LossTypesByIdOutput output = new LossTypesByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = LossTypesById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await LossTypesById_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = LossTypesById_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await LossTypesById_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

