// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductsQuery
//     Last Modified On: 12/27/2025 12:41:19 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the ProductsQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand ProductsQuery_BuildCommand(SqlConnection cnn, ProductsQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[ProductsQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Name",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 200,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Brand",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 200,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Category",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ContainerType",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Barcode",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Sku",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsActive",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = DBNull.Value
            });

            if (input.Name != null)
            {
                result.Parameters["@Name"].Value = input.Name;
            }
            if (input.Brand != null)
            {
                result.Parameters["@Brand"].Value = input.Brand;
            }
            if (input.Category != null)
            {
                result.Parameters["@Category"].Value = input.Category;
            }
            if (input.ContainerType != null)
            {
                result.Parameters["@ContainerType"].Value = input.ContainerType;
            }
            if (input.Barcode != null)
            {
                result.Parameters["@Barcode"].Value = input.Barcode;
            }
            if (input.Sku != null)
            {
                result.Parameters["@Sku"].Value = input.Sku;
            }
            if (input.IsActive != null)
            {
                result.Parameters["@IsActive"].Value = input.IsActive;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void ProductsQuery_SetParameters(SqlCommand cmd, ProductsQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (ProductsQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private ProductsQueryResult ProductsQuery_ResultData(SqlDataReader rdr)
        {
            return new ProductsQueryResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetString(2),
            rdr.GetInt32(3),
            rdr.GetInt32(4),
            rdr.GetString(5),
            rdr.GetDecimal(6),
            rdr.GetDecimal(7),
            rdr.IsDBNull(8) ? null : rdr.GetDecimal(8),
            rdr.IsDBNull(9) ? null : rdr.GetString(9),
            rdr.IsDBNull(10) ? null : rdr.GetString(10),
            rdr.GetBoolean(11),
            rdr.GetInt32(12),
            rdr.GetDateTime(13),
            rdr.GetDateTime(14)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void ProductsQuery_Execute(SqlCommand cmd, ProductsQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<ProductsQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(ProductsQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            ProductsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task ProductsQuery_ExecuteAsync(SqlCommand cmd, ProductsQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<ProductsQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(ProductsQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            ProductsQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.Products table.<br/>
        /// DB Routine: dbo.ProductsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductsQueryInput instance.</param>
        /// <returns>Instance of ProductsQueryOutput</returns>
        public ProductsQueryOutput ProductsQuery(ProductsQueryInput input)
        {
            ValidateInput(input, nameof(ProductsQuery));
            ProductsQueryOutput output = new ProductsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    ProductsQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductsQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						ProductsQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.Products table.<br/>
        /// DB Routine: dbo.ProductsQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductsQueryInput instance.</param>
        /// <returns>Instance of ProductsQueryOutput</returns>
        public async Task<ProductsQueryOutput> ProductsQueryAsync(ProductsQueryInput input)
        {
            ValidateInput(input, nameof(ProductsQueryAsync));
            ProductsQueryOutput output = new ProductsQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductsQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await ProductsQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductsQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await ProductsQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

