// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductCategoriesQuery
//     Last Modified On: 12/26/2025 11:15:04 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the ProductCategoriesQuery routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand ProductCategoriesQuery_BuildCommand(SqlConnection cnn, ProductCategoriesQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[ProductCategoriesQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Name",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SortOrder",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsActive",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = DBNull.Value
            });

            if (input.Name != null)
            {
                result.Parameters["@Name"].Value = input.Name;
            }
            if (input.SortOrder != null)
            {
                result.Parameters["@SortOrder"].Value = input.SortOrder;
            }
            if (input.IsActive != null)
            {
                result.Parameters["@IsActive"].Value = input.IsActive;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void ProductCategoriesQuery_SetParameters(SqlCommand cmd, ProductCategoriesQueryOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (ProductCategoriesQueryOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private ProductCategoriesQueryResult ProductCategoriesQuery_ResultData(SqlDataReader rdr)
        {
            return new ProductCategoriesQueryResult(
            rdr.GetByte(0),
            rdr.GetString(1),
            rdr.GetInt32(2),
            rdr.GetBoolean(3),
            rdr.GetDateTime(4),
            rdr.GetDateTime(5)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void ProductCategoriesQuery_Execute(SqlCommand cmd, ProductCategoriesQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<ProductCategoriesQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(ProductCategoriesQuery_ResultData(rdr));
                }
                rdr.Close();
            }

            ProductCategoriesQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task ProductCategoriesQuery_ExecuteAsync(SqlCommand cmd, ProductCategoriesQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<ProductCategoriesQueryResult>();
                while (await rdr.ReadAsync())
                {
                    output.ResultData.Add(ProductCategoriesQuery_ResultData(rdr));
                }
                await rdr.CloseAsync();
            }

            ProductCategoriesQuery_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Queries dbo.ProductCategories table.<br/>
        /// DB Routine: dbo.ProductCategoriesQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductCategoriesQueryInput instance.</param>
        /// <returns>Instance of ProductCategoriesQueryOutput</returns>
        public ProductCategoriesQueryOutput ProductCategoriesQuery(ProductCategoriesQueryInput input)
        {
            ValidateInput(input, nameof(ProductCategoriesQuery));
            ProductCategoriesQueryOutput output = new ProductCategoriesQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductCategoriesQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    ProductCategoriesQuery_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductCategoriesQuery_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						ProductCategoriesQuery_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Queries dbo.ProductCategories table.<br/>
        /// DB Routine: dbo.ProductCategoriesQuery<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductCategoriesQueryInput instance.</param>
        /// <returns>Instance of ProductCategoriesQueryOutput</returns>
        public async Task<ProductCategoriesQueryOutput> ProductCategoriesQueryAsync(ProductCategoriesQueryInput input)
        {
            ValidateInput(input, nameof(ProductCategoriesQueryAsync));
            ProductCategoriesQueryOutput output = new ProductCategoriesQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductCategoriesQuery_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await ProductCategoriesQuery_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductCategoriesQuery_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await ProductCategoriesQuery_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

