// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductsUpsert
//     Last Modified On: 12/27/2025 6:37:58 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the ProductsUpsert routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand ProductsUpsert_BuildCommand(SqlConnection cnn, ProductsUpsertInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[ProductsUpsert]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.InputOutput,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Name",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 200,
                Value = input.Name
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Brand",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 200,
                Value = input.Brand
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Category",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Category
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ContainerType",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.ContainerType
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SizeDescription",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = input.SizeDescription
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@UnitCost",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.UnitCost
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@UnitPrice",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = input.UnitPrice
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ServingsPerUnit",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Decimal,
                Scale = 2,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Barcode",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Sku",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 50,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IsActive",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Bit,
                Value = input.IsActive
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SortOrder",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.SortOrder
            });

            if (input.Id != null)
            {
                result.Parameters["@Id"].Value = input.Id;
            }
            if (input.ServingsPerUnit != null)
            {
                result.Parameters["@ServingsPerUnit"].Value = input.ServingsPerUnit;
            }
            if (input.Barcode != null)
            {
                result.Parameters["@Barcode"].Value = input.Barcode;
            }
            if (input.Sku != null)
            {
                result.Parameters["@Sku"].Value = input.Sku;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void ProductsUpsert_SetParameters(SqlCommand cmd, ProductsUpsertOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (ProductsUpsertOutput.Returns)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.Id = (int?)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void ProductsUpsert_Execute(SqlCommand cmd, ProductsUpsertOutput output)
        {
            cmd.ExecuteNonQuery();

            ProductsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task ProductsUpsert_ExecuteAsync(SqlCommand cmd, ProductsUpsertOutput output)
        {
            await cmd.ExecuteNonQueryAsync();

            ProductsUpsert_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Upserts a new record into the dbo.Products table.<br/>
        /// DB Routine: dbo.ProductsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductsUpsertInput instance.</param>
        /// <returns>Instance of ProductsUpsertOutput</returns>
        public ProductsUpsertOutput ProductsUpsert(ProductsUpsertInput input)
        {
            ValidateInput(input, nameof(ProductsUpsert));
            ProductsUpsertOutput output = new ProductsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    ProductsUpsert_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductsUpsert_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						ProductsUpsert_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Upserts a new record into the dbo.Products table.<br/>
        /// DB Routine: dbo.ProductsUpsert<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductsUpsertInput instance.</param>
        /// <returns>Instance of ProductsUpsertOutput</returns>
        public async Task<ProductsUpsertOutput> ProductsUpsertAsync(ProductsUpsertInput input)
        {
            ValidateInput(input, nameof(ProductsUpsertAsync));
            ProductsUpsertOutput output = new ProductsUpsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductsUpsert_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await ProductsUpsert_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductsUpsert_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await ProductsUpsert_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

