// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductCategoriesById
//     Last Modified On: 12/27/2025 12:41:19 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB
{
    #nullable enable

    #region Using Statments

    using BarInventory.BarDB.Models;
    using Microsoft.Data.SqlClient;
    using System;
    using System.Data;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the ProductCategoriesById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand ProductCategoriesById_BuildCommand(SqlConnection cnn, ProductCategoriesByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[ProductCategoriesById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.Id
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void ProductCategoriesById_SetParameters(SqlCommand cmd, ProductCategoriesByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (ProductCategoriesByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private ProductCategoriesByIdResult ProductCategoriesById_ResultData(SqlDataReader rdr)
        {
            return new ProductCategoriesByIdResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetInt32(2),
            rdr.GetBoolean(3),
            rdr.GetDateTime(4),
            rdr.GetDateTime(5)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void ProductCategoriesById_Execute(SqlCommand cmd, ProductCategoriesByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = ProductCategoriesById_ResultData(rdr);
                }
                rdr.Close();
            }

            ProductCategoriesById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Execute Command Async

        private async Task ProductCategoriesById_ExecuteAsync(SqlCommand cmd, ProductCategoriesByIdOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if (await rdr.ReadAsync())
                {
                    output.ResultData = ProductCategoriesById_ResultData(rdr);
                }
                await rdr.CloseAsync();
            }

            ProductCategoriesById_SetParameters(cmd, output);
        }

        #endregion Execute Command Async
        #region Public Service

        /// <summary>
        /// Selects single row from dbo.ProductCategories table by identity column.<br/>
        /// DB Routine: dbo.ProductCategoriesById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductCategoriesByIdInput instance.</param>
        /// <returns>Instance of ProductCategoriesByIdOutput</returns>
        public ProductCategoriesByIdOutput ProductCategoriesById(ProductCategoriesByIdInput input)
        {
            ValidateInput(input, nameof(ProductCategoriesById));
            ProductCategoriesByIdOutput output = new ProductCategoriesByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductCategoriesById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    ProductCategoriesById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductCategoriesById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						ProductCategoriesById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service
		#region Public Service Async

        /// <summary>
        /// Selects single row from dbo.ProductCategories table by identity column.<br/>
        /// DB Routine: dbo.ProductCategoriesById<br/>
        /// Author: Kirk Barrett<br/>
        /// </summary>
        /// <param name="input">ProductCategoriesByIdInput instance.</param>
        /// <returns>Instance of ProductCategoriesByIdOutput</returns>
        public async Task<ProductCategoriesByIdOutput> ProductCategoriesByIdAsync(ProductCategoriesByIdInput input)
        {
            ValidateInput(input, nameof(ProductCategoriesByIdAsync));
            ProductCategoriesByIdOutput output = new ProductCategoriesByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = ProductCategoriesById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
						await ProductCategoriesById_ExecuteAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = ProductCategoriesById_BuildCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await ProductCategoriesById_ExecuteAsync(cmd, output);
                        await cnn.CloseAsync();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion Public Service Async
    }
}

