// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AreaCountsQuery
//     Last Modified On: 12/27/2025 12:41:14 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the AreaCountsQuery service.
    /// </summary>
    public partial class AreaCountsQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for AreaCountsQueryInput.
        /// </summary>
        public AreaCountsQueryInput() { }

        /// <summary>
        /// Parameterized constructor for AreaCountsQueryInput.
        /// </summary>
        /// <param name="InventoryItemId">InventoryItemId</param>
        /// <param name="AreaId">AreaId</param>
        /// <param name="HasPartial">HasPartial</param>
        public AreaCountsQueryInput(int? InventoryItemId, int? AreaId, bool? HasPartial)
        {
            this.InventoryItemId = InventoryItemId;
            this.AreaId = AreaId;
            this.HasPartial = HasPartial;
        }

        #endregion Constructors

        #region Fields

        private int? _InventoryItemId = null;
        /// <summary>
        /// InventoryItemId
        /// </summary>
        public int? InventoryItemId
        {
            get => _InventoryItemId;
            set => _InventoryItemId = value;
        }

        private int? _AreaId = null;
        /// <summary>
        /// AreaId
        /// </summary>
        public int? AreaId
        {
            get => _AreaId;
            set => _AreaId = value;
        }

        private bool? _HasPartial = null;
        /// <summary>
        /// HasPartial
        /// </summary>
        public bool? HasPartial
        {
            get => _HasPartial;
            set => _HasPartial = value;
        }

        #endregion

    }
}