// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AreaCountsQuery
//     Last Modified On: 12/26/2025 8:28:00 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for AreaCountsQuery service.
    /// </summary>
    public partial class AreaCountsQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of AreaCountsQueryResult.
        /// </summary>
        public List<AreaCountsQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for AreaCountsQuery service.
    /// </summary>


    public partial class AreaCountsQueryResult
	{
        /// <summary>
        /// Result set object for AreaCountsQuery.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="InventoryItemId">Maps to table value column InventoryItemId.</param>
        /// <param name="AreaId">Maps to table value column AreaId.</param>
        /// <param name="FullUnits">Maps to table value column FullUnits.</param>
        /// <param name="PartialAmount">Maps to table value column PartialAmount.</param>
        /// <param name="HasPartial">Maps to table value column HasPartial.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        public AreaCountsQueryResult(int Id, int InventoryItemId, int AreaId, int FullUnits, decimal PartialAmount, bool HasPartial, DateTime CreatedAt, DateTime ModifiedAt)
        {
             this.Id = Id;
             this.InventoryItemId = InventoryItemId;
             this.AreaId = AreaId;
             this.FullUnits = FullUnits;
             this.PartialAmount = PartialAmount;
             this.HasPartial = HasPartial;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column InventoryItemId.
        /// </summary>
        public int InventoryItemId { set; get; }

        /// <summary>
        /// Maps to table value column AreaId.
        /// </summary>
        public int AreaId { set; get; }

        /// <summary>
        /// Maps to table value column FullUnits.
        /// </summary>
        public int FullUnits { set; get; }

        /// <summary>
        /// Maps to table value column PartialAmount.
        /// </summary>
        public decimal PartialAmount { set; get; }

        /// <summary>
        /// Maps to table value column HasPartial.
        /// </summary>
        public bool HasPartial { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime ModifiedAt { set; get; }
    }

    #endregion Result Set Objects

}
