// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AreaCountsUpsert
//     Last Modified On: 12/26/2025 9:12:02 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the AreaCountsUpsert service.
    /// </summary>
    public partial class AreaCountsUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for AreaCountsUpsertInput.
        /// </summary>
        public AreaCountsUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for AreaCountsUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="InventoryItemId">InventoryItemId</param>
        /// <param name="AreaId">AreaId</param>
        /// <param name="FullUnits">FullUnits</param>
        /// <param name="PartialAmount">PartialAmount</param>
        /// <param name="HasPartial">HasPartial</param>
        public AreaCountsUpsertInput(int? Id, int? InventoryItemId, int? AreaId, int? FullUnits, decimal? PartialAmount, bool? HasPartial)
        {
            this.Id = Id;
            this.InventoryItemId = InventoryItemId;
            this.AreaId = AreaId;
            this.FullUnits = FullUnits;
            this.PartialAmount = PartialAmount;
            this.HasPartial = HasPartial;
        }

        #endregion Constructors

        #region Fields

        private int? _Id = 0;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _InventoryItemId = 0;
        /// <summary>
        /// InventoryItemId
        /// </summary>
        [Required]
        public int? InventoryItemId
        {
            get => _InventoryItemId;
            set => _InventoryItemId = value;
        }

        private int? _AreaId = 0;
        /// <summary>
        /// AreaId
        /// </summary>
        [Required]
        public int? AreaId
        {
            get => _AreaId;
            set => _AreaId = value;
        }

        private int? _FullUnits = 0;
        /// <summary>
        /// FullUnits
        /// </summary>
        [Required]
        public int? FullUnits
        {
            get => _FullUnits;
            set => _FullUnits = value;
        }

        private decimal? _PartialAmount = 0;
        /// <summary>
        /// PartialAmount
        /// </summary>
        [Required]
        public decimal? PartialAmount
        {
            get => _PartialAmount;
            set => _PartialAmount = value;
        }

        private bool? _HasPartial = false;
        /// <summary>
        /// HasPartial
        /// </summary>
        [Required]
        public bool? HasPartial
        {
            get => _HasPartial;
            set => _HasPartial = value;
        }

        #endregion

    }
}