// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryItemsQuery
//     Last Modified On: 12/27/2025 12:41:17 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the InventoryItemsQuery service.
    /// </summary>
    public partial class InventoryItemsQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for InventoryItemsQueryInput.
        /// </summary>
        public InventoryItemsQueryInput() { }

        /// <summary>
        /// Parameterized constructor for InventoryItemsQueryInput.
        /// </summary>
        /// <param name="SessionId">SessionId</param>
        /// <param name="ProductId">ProductId</param>
        public InventoryItemsQueryInput(int? SessionId, int? ProductId)
        {
            this.SessionId = SessionId;
            this.ProductId = ProductId;
        }

        #endregion Constructors

        #region Fields

        private int? _SessionId = null;
        /// <summary>
        /// SessionId
        /// </summary>
        public int? SessionId
        {
            get => _SessionId;
            set => _SessionId = value;
        }

        private int? _ProductId = null;
        /// <summary>
        /// ProductId
        /// </summary>
        public int? ProductId
        {
            get => _ProductId;
            set => _ProductId = value;
        }

        #endregion

    }
}