// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryItemsQuery
//     Last Modified On: 12/26/2025 8:32:34 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for InventoryItemsQuery service.
    /// </summary>
    public partial class InventoryItemsQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of InventoryItemsQueryResult.
        /// </summary>
        public List<InventoryItemsQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for InventoryItemsQuery service.
    /// </summary>


    public partial class InventoryItemsQueryResult
	{
        /// <summary>
        /// Result set object for InventoryItemsQuery.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="SessionId">Maps to table value column SessionId.</param>
        /// <param name="ProductId">Maps to table value column ProductId.</param>
        /// <param name="UnitCost">Maps to table value column UnitCost.</param>
        /// <param name="StartingQuantity">Maps to table value column StartingQuantity.</param>
        /// <param name="ReceivedQuantity">Maps to table value column ReceivedQuantity.</param>
        /// <param name="ReceivedCost">Maps to table value column ReceivedCost.</param>
        /// <param name="ComputerSold">Maps to table value column ComputerSold.</param>
        /// <param name="CreditedProduct">Maps to table value column CreditedProduct.</param>
        /// <param name="LastCountedAt">Maps to table value column LastCountedAt.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        public InventoryItemsQueryResult(int Id, int SessionId, int ProductId, decimal UnitCost, decimal StartingQuantity, decimal ReceivedQuantity, decimal ReceivedCost, decimal ComputerSold, decimal CreditedProduct, DateTime? LastCountedAt, DateTime CreatedAt, DateTime ModifiedAt)
        {
             this.Id = Id;
             this.SessionId = SessionId;
             this.ProductId = ProductId;
             this.UnitCost = UnitCost;
             this.StartingQuantity = StartingQuantity;
             this.ReceivedQuantity = ReceivedQuantity;
             this.ReceivedCost = ReceivedCost;
             this.ComputerSold = ComputerSold;
             this.CreditedProduct = CreditedProduct;
             this.LastCountedAt = LastCountedAt;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column SessionId.
        /// </summary>
        public int SessionId { set; get; }

        /// <summary>
        /// Maps to table value column ProductId.
        /// </summary>
        public int ProductId { set; get; }

        /// <summary>
        /// Maps to table value column UnitCost.
        /// </summary>
        public decimal UnitCost { set; get; }

        /// <summary>
        /// Maps to table value column StartingQuantity.
        /// </summary>
        public decimal StartingQuantity { set; get; }

        /// <summary>
        /// Maps to table value column ReceivedQuantity.
        /// </summary>
        public decimal ReceivedQuantity { set; get; }

        /// <summary>
        /// Maps to table value column ReceivedCost.
        /// </summary>
        public decimal ReceivedCost { set; get; }

        /// <summary>
        /// Maps to table value column ComputerSold.
        /// </summary>
        public decimal ComputerSold { set; get; }

        /// <summary>
        /// Maps to table value column CreditedProduct.
        /// </summary>
        public decimal CreditedProduct { set; get; }

        /// <summary>
        /// Maps to table value column LastCountedAt.
        /// </summary>
        public DateTime? LastCountedAt { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime ModifiedAt { set; get; }
    }

    #endregion Result Set Objects

}
