// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryItemsUpsert
//     Last Modified On: 12/26/2025 8:59:37 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the InventoryItemsUpsert service.
    /// </summary>
    public partial class InventoryItemsUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for InventoryItemsUpsertInput.
        /// </summary>
        public InventoryItemsUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for InventoryItemsUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="SessionId">SessionId</param>
        /// <param name="ProductId">ProductId</param>
        /// <param name="UnitCost">UnitCost</param>
        /// <param name="StartingQuantity">StartingQuantity</param>
        /// <param name="ReceivedQuantity">ReceivedQuantity</param>
        /// <param name="ReceivedCost">ReceivedCost</param>
        /// <param name="ComputerSold">ComputerSold</param>
        /// <param name="CreditedProduct">CreditedProduct</param>
        /// <param name="LastCountedAt">LastCountedAt</param>
        public InventoryItemsUpsertInput(int? Id, int? SessionId, int? ProductId, decimal? UnitCost, decimal? StartingQuantity, decimal? ReceivedQuantity, decimal? ReceivedCost, decimal? ComputerSold, decimal? CreditedProduct, DateTime? LastCountedAt)
        {
            this.Id = Id;
            this.SessionId = SessionId;
            this.ProductId = ProductId;
            this.UnitCost = UnitCost;
            this.StartingQuantity = StartingQuantity;
            this.ReceivedQuantity = ReceivedQuantity;
            this.ReceivedCost = ReceivedCost;
            this.ComputerSold = ComputerSold;
            this.CreditedProduct = CreditedProduct;
            this.LastCountedAt = LastCountedAt;
        }

        #endregion Constructors

        #region Fields

        private int? _Id = 0;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _SessionId = 0;
        /// <summary>
        /// SessionId
        /// </summary>
        [Required]
        public int? SessionId
        {
            get => _SessionId;
            set => _SessionId = value;
        }

        private int? _ProductId = 0;
        /// <summary>
        /// ProductId
        /// </summary>
        [Required]
        public int? ProductId
        {
            get => _ProductId;
            set => _ProductId = value;
        }

        private decimal? _UnitCost = 0;
        /// <summary>
        /// UnitCost
        /// </summary>
        [Required]
        public decimal? UnitCost
        {
            get => _UnitCost;
            set => _UnitCost = value;
        }

        private decimal? _StartingQuantity = 0;
        /// <summary>
        /// StartingQuantity
        /// </summary>
        [Required]
        public decimal? StartingQuantity
        {
            get => _StartingQuantity;
            set => _StartingQuantity = value;
        }

        private decimal? _ReceivedQuantity = 0;
        /// <summary>
        /// ReceivedQuantity
        /// </summary>
        [Required]
        public decimal? ReceivedQuantity
        {
            get => _ReceivedQuantity;
            set => _ReceivedQuantity = value;
        }

        private decimal? _ReceivedCost = 0;
        /// <summary>
        /// ReceivedCost
        /// </summary>
        [Required]
        public decimal? ReceivedCost
        {
            get => _ReceivedCost;
            set => _ReceivedCost = value;
        }

        private decimal? _ComputerSold = 0;
        /// <summary>
        /// ComputerSold
        /// </summary>
        [Required]
        public decimal? ComputerSold
        {
            get => _ComputerSold;
            set => _ComputerSold = value;
        }

        private decimal? _CreditedProduct = 0;
        /// <summary>
        /// CreditedProduct
        /// </summary>
        [Required]
        public decimal? CreditedProduct
        {
            get => _CreditedProduct;
            set => _CreditedProduct = value;
        }

        private DateTime? _LastCountedAt = null;
        /// <summary>
        /// LastCountedAt
        /// </summary>
        public DateTime? LastCountedAt
        {
            get => _LastCountedAt;
            set => _LastCountedAt = value;
        }

        #endregion

    }
}