// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventorySessionsQuery
//     Last Modified On: 12/27/2025 12:41:17 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the InventorySessionsQuery service.
    /// </summary>
    public partial class InventorySessionsQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for InventorySessionsQueryInput.
        /// </summary>
        public InventorySessionsQueryInput() { }

        /// <summary>
        /// Parameterized constructor for InventorySessionsQueryInput.
        /// </summary>
        /// <param name="SessionName">SessionName</param>
        /// <param name="IsComplete">IsComplete</param>
        /// <param name="CountedBy">CountedBy</param>
        public InventorySessionsQueryInput(string? SessionName, bool? IsComplete, string? CountedBy)
        {
            this.SessionName = SessionName;
            this.IsComplete = IsComplete;
            this.CountedBy = CountedBy;
        }

        #endregion Constructors

        #region Fields

        private string? _SessionName = null;
        /// <summary>
        /// SessionName
        /// </summary>
        public string? SessionName
        {
            get => _SessionName;
            set => _SessionName = value;
        }

        private bool? _IsComplete = null;
        /// <summary>
        /// IsComplete
        /// </summary>
        public bool? IsComplete
        {
            get => _IsComplete;
            set => _IsComplete = value;
        }

        private string? _CountedBy = null;
        /// <summary>
        /// CountedBy
        /// </summary>
        public string? CountedBy
        {
            get => _CountedBy;
            set => _CountedBy = value;
        }

        #endregion

    }
}