// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventorySessionsUpsert
//     Last Modified On: 12/27/2025 6:38:40 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the InventorySessionsUpsert service.
    /// </summary>
    public partial class InventorySessionsUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for InventorySessionsUpsertInput.
        /// </summary>
        public InventorySessionsUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for InventorySessionsUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="SessionName">SessionName</param>
        /// <param name="SessionDate">SessionDate</param>
        /// <param name="CompletedAt">CompletedAt</param>
        /// <param name="Frequency">Frequency</param>
        /// <param name="Notes">Notes</param>
        /// <param name="IsComplete">IsComplete</param>
        /// <param name="CountedBy">CountedBy</param>
        public InventorySessionsUpsertInput(int? Id, string? SessionName, DateTime? SessionDate, DateTime? CompletedAt, int? Frequency, string? Notes, bool? IsComplete, string? CountedBy)
        {
            this.Id = Id;
            this.SessionName = SessionName;
            this.SessionDate = SessionDate;
            this.CompletedAt = CompletedAt;
            this.Frequency = Frequency;
            this.Notes = Notes;
            this.IsComplete = IsComplete;
            this.CountedBy = CountedBy;
        }

        #endregion Constructors

        #region Fields

        private int? _Id = null;
        /// <summary>
        /// Id
        /// </summary>
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private string? _SessionName = "";
        /// <summary>
        /// SessionName
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string? SessionName
        {
            get => _SessionName;
            set => _SessionName = value;
        }

        private DateTime? _SessionDate = System.DateTime.Now;
        /// <summary>
        /// SessionDate
        /// </summary>
        [Required]
        public DateTime? SessionDate
        {
            get => _SessionDate;
            set => _SessionDate = value;
        }

        private DateTime? _CompletedAt = null;
        /// <summary>
        /// CompletedAt
        /// </summary>
        public DateTime? CompletedAt
        {
            get => _CompletedAt;
            set => _CompletedAt = value;
        }

        private int? _Frequency = 0;
        /// <summary>
        /// Frequency
        /// </summary>
        [Required]
        public int? Frequency
        {
            get => _Frequency;
            set => _Frequency = value;
        }

        private string? _Notes = null;
        /// <summary>
        /// Notes
        /// </summary>
        public string? Notes
        {
            get => _Notes;
            set => _Notes = value;
        }

        private bool? _IsComplete = true;
        /// <summary>
        /// IsComplete
        /// </summary>
        [Required]
        public bool? IsComplete
        {
            get => _IsComplete;
            set => _IsComplete = value;
        }

        private string? _CountedBy;
        /// <summary>
        /// CountedBy
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string? CountedBy
        {
            get => _CountedBy;
            set => _CountedBy = value;
        }

        #endregion

    }
}