// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventorySessionsDelete
//     Last Modified On: 12/27/2025 12:41:17 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the InventorySessionsDelete service.
    /// </summary>
    public partial class InventorySessionsDeleteInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for InventorySessionsDeleteInput.
        /// </summary>
        public InventorySessionsDeleteInput() { }

        /// <summary>
        /// Parameterized constructor for InventorySessionsDeleteInput.
        /// </summary>
        /// <param name="Id">Id</param>
        public InventorySessionsDeleteInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}