// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryFrequenciesById
//     Last Modified On: 12/26/2025 11:30:19 PM
//     Written By: Kirk Barrett
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for InventoryFrequenciesById service.
    /// </summary>
    public partial class InventoryFrequenciesByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of InventoryFrequenciesByIdResult.
        /// </summary>
        public InventoryFrequenciesByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for InventoryFrequenciesById service.
    /// </summary>


    public partial class InventoryFrequenciesByIdResult
	{
        /// <summary>
        /// Result set object for InventoryFrequenciesById.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="SortOrder">Maps to table value column SortOrder.</param>
        /// <param name="IsActive">Maps to table value column IsActive.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        public InventoryFrequenciesByIdResult(byte Id, string Name, int SortOrder, bool IsActive, DateTime CreatedAt, DateTime ModifiedAt)
        {
             this.Id = Id;
             this.Name = Name;
             this.SortOrder = SortOrder;
             this.IsActive = IsActive;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public byte Id { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column SortOrder.
        /// </summary>
        public int SortOrder { set; get; }

        /// <summary>
        /// Maps to table value column IsActive.
        /// </summary>
        public bool IsActive { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime ModifiedAt { set; get; }
    }

    #endregion Result Set Objects

}
