// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryAreasQuery
//     Last Modified On: 12/27/2025 12:41:16 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the InventoryAreasQuery service.
    /// </summary>
    public partial class InventoryAreasQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for InventoryAreasQueryInput.
        /// </summary>
        public InventoryAreasQueryInput() { }

        /// <summary>
        /// Parameterized constructor for InventoryAreasQueryInput.
        /// </summary>
        /// <param name="Name">Name</param>
        /// <param name="ShortCode">ShortCode</param>
        /// <param name="IsActive">IsActive</param>
        public InventoryAreasQueryInput(string? Name, string? ShortCode, bool? IsActive)
        {
            this.Name = Name;
            this.ShortCode = ShortCode;
            this.IsActive = IsActive;
        }

        #endregion Constructors

        #region Fields

        private string? _Name = null;
        /// <summary>
        /// Name
        /// </summary>
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        private string? _ShortCode = null;
        /// <summary>
        /// ShortCode
        /// </summary>
        public string? ShortCode
        {
            get => _ShortCode;
            set => _ShortCode = value;
        }

        private bool? _IsActive = null;
        /// <summary>
        /// IsActive
        /// </summary>
        public bool? IsActive
        {
            get => _IsActive;
            set => _IsActive = value;
        }

        #endregion

    }
}