// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventoryAreasUpsert
//     Last Modified On: 12/26/2025 8:59:10 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the InventoryAreasUpsert service.
    /// </summary>
    public partial class InventoryAreasUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for InventoryAreasUpsertInput.
        /// </summary>
        public InventoryAreasUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for InventoryAreasUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="Name">Name</param>
        /// <param name="ShortCode">ShortCode</param>
        /// <param name="SortOrder">SortOrder</param>
        /// <param name="IsActive">IsActive</param>
        public InventoryAreasUpsertInput(int? Id, string? Name, string? ShortCode, int? SortOrder, bool? IsActive)
        {
            this.Id = Id;
            this.Name = Name;
            this.ShortCode = ShortCode;
            this.SortOrder = SortOrder;
            this.IsActive = IsActive;
        }

        #endregion Constructors

        #region Fields

        private int? _Id = 0;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private string? _Name = "";
        /// <summary>
        /// Name
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        private string? _ShortCode = "";
        /// <summary>
        /// ShortCode
        /// </summary>
        [Required]
        [MaxLength(10)]
        public string? ShortCode
        {
            get => _ShortCode;
            set => _ShortCode = value;
        }

        private int? _SortOrder = 0;
        /// <summary>
        /// SortOrder
        /// </summary>
        [Required]
        public int? SortOrder
        {
            get => _SortOrder;
            set => _SortOrder = value;
        }

        private bool? _IsActive = true;
        /// <summary>
        /// IsActive
        /// </summary>
        [Required]
        public bool? IsActive
        {
            get => _IsActive;
            set => _IsActive = value;
        }

        #endregion

    }
}