// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: InventorySessionsQuery
//     Last Modified On: 12/26/2025 9:03:50 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for InventorySessionsQuery service.
    /// </summary>
    public partial class InventorySessionsQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of InventorySessionsQueryResult.
        /// </summary>
        public List<InventorySessionsQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for InventorySessionsQuery service.
    /// </summary>


    public partial class InventorySessionsQueryResult
	{
        /// <summary>
        /// Result set object for InventorySessionsQuery.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="SessionName">Maps to table value column SessionName.</param>
        /// <param name="SessionDate">Maps to table value column SessionDate.</param>
        /// <param name="CompletedAt">Maps to table value column CompletedAt.</param>
        /// <param name="Frequency">Maps to table value column Frequency.</param>
        /// <param name="Notes">Maps to table value column Notes.</param>
        /// <param name="IsComplete">Maps to table value column IsComplete.</param>
        /// <param name="CountedBy">Maps to table value column CountedBy.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        public InventorySessionsQueryResult(int Id, string SessionName, DateTime SessionDate, DateTime? CompletedAt, byte Frequency, string? Notes, bool IsComplete, string CountedBy, DateTime CreatedAt, DateTime ModifiedAt)
        {
             this.Id = Id;
             this.SessionName = SessionName;
             this.SessionDate = SessionDate;
             this.CompletedAt = CompletedAt;
             this.Frequency = Frequency;
             this.Notes = Notes;
             this.IsComplete = IsComplete;
             this.CountedBy = CountedBy;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column SessionName.
        /// </summary>
        public string SessionName { set; get; }

        /// <summary>
        /// Maps to table value column SessionDate.
        /// </summary>
        public DateTime SessionDate { set; get; }

        /// <summary>
        /// Maps to table value column CompletedAt.
        /// </summary>
        public DateTime? CompletedAt { set; get; }

        /// <summary>
        /// Maps to table value column Frequency.
        /// </summary>
        public byte Frequency { set; get; }

        /// <summary>
        /// Maps to table value column Notes.
        /// </summary>
        public string? Notes { set; get; }

        /// <summary>
        /// Maps to table value column IsComplete.
        /// </summary>
        public bool IsComplete { set; get; }

        /// <summary>
        /// Maps to table value column CountedBy.
        /// </summary>
        public string CountedBy { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime ModifiedAt { set; get; }
    }

    #endregion Result Set Objects

}
