// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossRecordsUpsert
//     Last Modified On: 12/26/2025 9:08:04 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the LossRecordsUpsert service.
    /// </summary>
    public partial class LossRecordsUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for LossRecordsUpsertInput.
        /// </summary>
        public LossRecordsUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for LossRecordsUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="SessionId">SessionId</param>
        /// <param name="ProductId">ProductId</param>
        /// <param name="LossType">LossType</param>
        /// <param name="Quantity">Quantity</param>
        /// <param name="EstimatedValue">EstimatedValue</param>
        /// <param name="Reason">Reason</param>
        /// <param name="RecordedBy">RecordedBy</param>
        /// <param name="OccurredAt">OccurredAt</param>
        public LossRecordsUpsertInput(int? Id, int? SessionId, int? ProductId, byte? LossType, decimal? Quantity, decimal? EstimatedValue, string? Reason, string? RecordedBy, DateTime? OccurredAt)
        {
            this.Id = Id;
            this.SessionId = SessionId;
            this.ProductId = ProductId;
            this.LossType = LossType;
            this.Quantity = Quantity;
            this.EstimatedValue = EstimatedValue;
            this.Reason = Reason;
            this.RecordedBy = RecordedBy;
            this.OccurredAt = OccurredAt;
        }

        #endregion Constructors

        #region Fields

        private int? _Id = 0;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _SessionId = 0;
        /// <summary>
        /// SessionId
        /// </summary>
        [Required]
        public int? SessionId
        {
            get => _SessionId;
            set => _SessionId = value;
        }

        private int? _ProductId = 0;
        /// <summary>
        /// ProductId
        /// </summary>
        [Required]
        public int? ProductId
        {
            get => _ProductId;
            set => _ProductId = value;
        }

        private byte? _LossType = 0;
        /// <summary>
        /// LossType
        /// </summary>
        [Required]
        public byte? LossType
        {
            get => _LossType;
            set => _LossType = value;
        }

        private decimal? _Quantity;
        /// <summary>
        /// Quantity
        /// </summary>
        [Required]
        public decimal? Quantity
        {
            get => _Quantity;
            set => _Quantity = value;
        }

        private decimal? _EstimatedValue;
        /// <summary>
        /// EstimatedValue
        /// </summary>
        [Required]
        public decimal? EstimatedValue
        {
            get => _EstimatedValue;
            set => _EstimatedValue = value;
        }

        private string? _Reason = null;
        /// <summary>
        /// Reason
        /// </summary>
        [MaxLength(500)]
        public string? Reason
        {
            get => _Reason;
            set => _Reason = value;
        }

        private string? _RecordedBy = null;
        /// <summary>
        /// RecordedBy
        /// </summary>
        [MaxLength(100)]
        public string? RecordedBy
        {
            get => _RecordedBy;
            set => _RecordedBy = value;
        }

        private DateTime? _OccurredAt = System.DateTime.Now;
        /// <summary>
        /// OccurredAt
        /// </summary>
        [Required]
        public DateTime? OccurredAt
        {
            get => _OccurredAt;
            set => _OccurredAt = value;
        }

        #endregion

    }
}