// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossRecordsById
//     Last Modified On: 12/27/2025 12:41:18 AM
//     Written By: Kirk Barrett
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for LossRecordsById service.
    /// </summary>
    public partial class LossRecordsByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of LossRecordsByIdResult.
        /// </summary>
        public LossRecordsByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for LossRecordsById service.
    /// </summary>


    public partial class LossRecordsByIdResult
	{
        /// <summary>
        /// Result set object for LossRecordsById.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="SessionId">Maps to table value column SessionId.</param>
        /// <param name="ProductId">Maps to table value column ProductId.</param>
        /// <param name="LossType">Maps to table value column LossType.</param>
        /// <param name="Quantity">Maps to table value column Quantity.</param>
        /// <param name="EstimatedValue">Maps to table value column EstimatedValue.</param>
        /// <param name="Reason">Maps to table value column Reason.</param>
        /// <param name="RecordedBy">Maps to table value column RecordedBy.</param>
        /// <param name="OccurredAt">Maps to table value column OccurredAt.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        public LossRecordsByIdResult(int Id, int SessionId, int ProductId, int LossType, decimal Quantity, decimal EstimatedValue, string? Reason, string? RecordedBy, DateTime OccurredAt, DateTime CreatedAt, DateTime ModifiedAt)
        {
             this.Id = Id;
             this.SessionId = SessionId;
             this.ProductId = ProductId;
             this.LossType = LossType;
             this.Quantity = Quantity;
             this.EstimatedValue = EstimatedValue;
             this.Reason = Reason;
             this.RecordedBy = RecordedBy;
             this.OccurredAt = OccurredAt;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column SessionId.
        /// </summary>
        public int SessionId { set; get; }

        /// <summary>
        /// Maps to table value column ProductId.
        /// </summary>
        public int ProductId { set; get; }

        /// <summary>
        /// Maps to table value column LossType.
        /// </summary>
        public int LossType { set; get; }

        /// <summary>
        /// Maps to table value column Quantity.
        /// </summary>
        public decimal Quantity { set; get; }

        /// <summary>
        /// Maps to table value column EstimatedValue.
        /// </summary>
        public decimal EstimatedValue { set; get; }

        /// <summary>
        /// Maps to table value column Reason.
        /// </summary>
        public string? Reason { set; get; }

        /// <summary>
        /// Maps to table value column RecordedBy.
        /// </summary>
        public string? RecordedBy { set; get; }

        /// <summary>
        /// Maps to table value column OccurredAt.
        /// </summary>
        public DateTime OccurredAt { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime ModifiedAt { set; get; }
    }

    #endregion Result Set Objects

}
