// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LossRecordsQuery
//     Last Modified On: 12/26/2025 9:08:04 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the LossRecordsQuery service.
    /// </summary>
    public partial class LossRecordsQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for LossRecordsQueryInput.
        /// </summary>
        public LossRecordsQueryInput() { }

        /// <summary>
        /// Parameterized constructor for LossRecordsQueryInput.
        /// </summary>
        /// <param name="SessionId">SessionId</param>
        /// <param name="ProductId">ProductId</param>
        /// <param name="LossType">LossType</param>
        public LossRecordsQueryInput(int? SessionId, int? ProductId, byte? LossType)
        {
            this.SessionId = SessionId;
            this.ProductId = ProductId;
            this.LossType = LossType;
        }

        #endregion Constructors

        #region Fields

        private int? _SessionId = null;
        /// <summary>
        /// SessionId
        /// </summary>
        public int? SessionId
        {
            get => _SessionId;
            set => _SessionId = value;
        }

        private int? _ProductId = null;
        /// <summary>
        /// ProductId
        /// </summary>
        public int? ProductId
        {
            get => _ProductId;
            set => _ProductId = value;
        }

        private byte? _LossType = null;
        /// <summary>
        /// LossType
        /// </summary>
        public byte? LossType
        {
            get => _LossType;
            set => _LossType = value;
        }

        #endregion

    }
}