// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductCategoriesQuery
//     Last Modified On: 12/26/2025 11:15:04 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the ProductCategoriesQuery service.
    /// </summary>
    public partial class ProductCategoriesQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ProductCategoriesQueryInput.
        /// </summary>
        public ProductCategoriesQueryInput() { }

        /// <summary>
        /// Parameterized constructor for ProductCategoriesQueryInput.
        /// </summary>
        /// <param name="Name">Name</param>
        /// <param name="SortOrder">SortOrder</param>
        /// <param name="IsActive">IsActive</param>
        public ProductCategoriesQueryInput(string? Name, int? SortOrder, bool? IsActive)
        {
            this.Name = Name;
            this.SortOrder = SortOrder;
            this.IsActive = IsActive;
        }

        #endregion Constructors

        #region Fields

        private string? _Name = null;
        /// <summary>
        /// Name
        /// </summary>
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        private int? _SortOrder = null;
        /// <summary>
        /// SortOrder
        /// </summary>
        public int? SortOrder
        {
            get => _SortOrder;
            set => _SortOrder = value;
        }

        private bool? _IsActive = null;
        /// <summary>
        /// IsActive
        /// </summary>
        public bool? IsActive
        {
            get => _IsActive;
            set => _IsActive = value;
        }

        #endregion

    }
}