// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductCategoriesUpsert
//     Last Modified On: 12/26/2025 11:15:03 PM
//     Written By: Kirk Barrett
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable
    /// <summary>
    /// Output object for ProductCategoriesUpsert service.
    /// </summary>
    public partial class ProductCategoriesUpsertOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for InsertError
            /// </summary>
             InsertError = 2,
            /// <summary>
            /// Enumerated value for UpdateError
            /// </summary>
             UpdateError = 3,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Id
        /// </summary>
        public byte? Id { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
