// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductsUpsert
//     Last Modified On: 12/27/2025 6:37:58 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the ProductsUpsert service.
    /// </summary>
    public partial class ProductsUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ProductsUpsertInput.
        /// </summary>
        public ProductsUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for ProductsUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="Name">Name</param>
        /// <param name="Brand">Brand</param>
        /// <param name="Category">Category</param>
        /// <param name="ContainerType">ContainerType</param>
        /// <param name="SizeDescription">SizeDescription</param>
        /// <param name="UnitCost">UnitCost</param>
        /// <param name="UnitPrice">UnitPrice</param>
        /// <param name="ServingsPerUnit">ServingsPerUnit</param>
        /// <param name="Barcode">Barcode</param>
        /// <param name="Sku">Sku</param>
        /// <param name="IsActive">IsActive</param>
        /// <param name="SortOrder">SortOrder</param>
        public ProductsUpsertInput(int? Id, string? Name, string? Brand, int? Category, int? ContainerType, string? SizeDescription, decimal? UnitCost, decimal? UnitPrice, decimal? ServingsPerUnit, string? Barcode, string? Sku, bool? IsActive, int? SortOrder)
        {
            this.Id = Id;
            this.Name = Name;
            this.Brand = Brand;
            this.Category = Category;
            this.ContainerType = ContainerType;
            this.SizeDescription = SizeDescription;
            this.UnitCost = UnitCost;
            this.UnitPrice = UnitPrice;
            this.ServingsPerUnit = ServingsPerUnit;
            this.Barcode = Barcode;
            this.Sku = Sku;
            this.IsActive = IsActive;
            this.SortOrder = SortOrder;
        }

        #endregion Constructors

        #region Fields

        private int? _Id = null;
        /// <summary>
        /// Id
        /// </summary>
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private string? _Name = "";
        /// <summary>
        /// Name
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        private string? _Brand = "";
        /// <summary>
        /// Brand
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string? Brand
        {
            get => _Brand;
            set => _Brand = value;
        }

        private int? _Category = 1;
        /// <summary>
        /// Category
        /// </summary>
        [Required]
        public int? Category
        {
            get => _Category;
            set => _Category = value;
        }

        private int? _ContainerType = 0;
        /// <summary>
        /// ContainerType
        /// </summary>
        [Required]
        public int? ContainerType
        {
            get => _ContainerType;
            set => _ContainerType = value;
        }

        private string? _SizeDescription = "";
        /// <summary>
        /// SizeDescription
        /// </summary>
        [Required]
        [MaxLength(50)]
        public string? SizeDescription
        {
            get => _SizeDescription;
            set => _SizeDescription = value;
        }

        private decimal? _UnitCost = 0;
        /// <summary>
        /// UnitCost
        /// </summary>
        [Required]
        public decimal? UnitCost
        {
            get => _UnitCost;
            set => _UnitCost = value;
        }

        private decimal? _UnitPrice = 0;
        /// <summary>
        /// UnitPrice
        /// </summary>
        [Required]
        public decimal? UnitPrice
        {
            get => _UnitPrice;
            set => _UnitPrice = value;
        }

        private decimal? _ServingsPerUnit = 0;
        /// <summary>
        /// ServingsPerUnit
        /// </summary>
        public decimal? ServingsPerUnit
        {
            get => _ServingsPerUnit;
            set => _ServingsPerUnit = value;
        }

        private string? _Barcode = null;
        /// <summary>
        /// Barcode
        /// </summary>
        [MaxLength(50)]
        public string? Barcode
        {
            get => _Barcode;
            set => _Barcode = value;
        }

        private string? _Sku = null;
        /// <summary>
        /// Sku
        /// </summary>
        [MaxLength(50)]
        public string? Sku
        {
            get => _Sku;
            set => _Sku = value;
        }

        private bool? _IsActive = true;
        /// <summary>
        /// IsActive
        /// </summary>
        [Required]
        public bool? IsActive
        {
            get => _IsActive;
            set => _IsActive = value;
        }

        private int? _SortOrder = 0;
        /// <summary>
        /// SortOrder
        /// </summary>
        [Required]
        public int? SortOrder
        {
            get => _SortOrder;
            set => _SortOrder = value;
        }

        #endregion

    }
}