// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductsById
//     Last Modified On: 12/26/2025 9:10:11 PM
//     Written By: Kirk Barrett
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for ProductsById service.
    /// </summary>
    public partial class ProductsByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of ProductsByIdResult.
        /// </summary>
        public ProductsByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for ProductsById service.
    /// </summary>


    public partial class ProductsByIdResult
	{
        /// <summary>
        /// Result set object for ProductsById.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Brand">Maps to table value column Brand.</param>
        /// <param name="Category">Maps to table value column Category.</param>
        /// <param name="ContainerType">Maps to table value column ContainerType.</param>
        /// <param name="SizeDescription">Maps to table value column SizeDescription.</param>
        /// <param name="UnitCost">Maps to table value column UnitCost.</param>
        /// <param name="UnitPrice">Maps to table value column UnitPrice.</param>
        /// <param name="ServingsPerUnit">Maps to table value column ServingsPerUnit.</param>
        /// <param name="Barcode">Maps to table value column Barcode.</param>
        /// <param name="Sku">Maps to table value column Sku.</param>
        /// <param name="IsActive">Maps to table value column IsActive.</param>
        /// <param name="SortOrder">Maps to table value column SortOrder.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        public ProductsByIdResult(int Id, string Name, string Brand, byte Category, byte ContainerType, string SizeDescription, decimal UnitCost, decimal UnitPrice, decimal? ServingsPerUnit, string? Barcode, string? Sku, bool IsActive, int SortOrder, DateTime CreatedAt, DateTime ModifiedAt)
        {
             this.Id = Id;
             this.Name = Name;
             this.Brand = Brand;
             this.Category = Category;
             this.ContainerType = ContainerType;
             this.SizeDescription = SizeDescription;
             this.UnitCost = UnitCost;
             this.UnitPrice = UnitPrice;
             this.ServingsPerUnit = ServingsPerUnit;
             this.Barcode = Barcode;
             this.Sku = Sku;
             this.IsActive = IsActive;
             this.SortOrder = SortOrder;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Brand.
        /// </summary>
        public string Brand { set; get; }

        /// <summary>
        /// Maps to table value column Category.
        /// </summary>
        public byte Category { set; get; }

        /// <summary>
        /// Maps to table value column ContainerType.
        /// </summary>
        public byte ContainerType { set; get; }

        /// <summary>
        /// Maps to table value column SizeDescription.
        /// </summary>
        public string SizeDescription { set; get; }

        /// <summary>
        /// Maps to table value column UnitCost.
        /// </summary>
        public decimal UnitCost { set; get; }

        /// <summary>
        /// Maps to table value column UnitPrice.
        /// </summary>
        public decimal UnitPrice { set; get; }

        /// <summary>
        /// Maps to table value column ServingsPerUnit.
        /// </summary>
        public decimal? ServingsPerUnit { set; get; }

        /// <summary>
        /// Maps to table value column Barcode.
        /// </summary>
        public string? Barcode { set; get; }

        /// <summary>
        /// Maps to table value column Sku.
        /// </summary>
        public string? Sku { set; get; }

        /// <summary>
        /// Maps to table value column IsActive.
        /// </summary>
        public bool IsActive { set; get; }

        /// <summary>
        /// Maps to table value column SortOrder.
        /// </summary>
        public int SortOrder { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime ModifiedAt { set; get; }
    }

    #endregion Result Set Objects

}
