// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ProductCategoriesDelete
//     Last Modified On: 12/26/2025 11:15:04 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace BarInventory.BarDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the ProductCategoriesDelete service.
    /// </summary>
    public partial class ProductCategoriesDeleteInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ProductCategoriesDeleteInput.
        /// </summary>
        public ProductCategoriesDeleteInput() { }

        /// <summary>
        /// Parameterized constructor for ProductCategoriesDeleteInput.
        /// </summary>
        /// <param name="Id">Id</param>
        public ProductCategoriesDeleteInput(byte? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private byte? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public byte? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}